### ISSUE TITLE
Fix raster layers not loading

### ISSUE THREAD

**Issue by vogelino** [vogelino/data-2-resilience#93]
The raster layers on the heat atlas page do not load. Ensure everything works as expected.

**Comment by vogelino** [comment]
@alsino @jkittner Fixed! The layer ID was the same for each hour of the day which caused issues. This should now work as expected.

**Comment by alsino** [comment]
@vogelino Great! It works again.

One little bug: It seems that the radio button in the left sidebar now does not show the selected layer on startup (see below):

![Image](https://github.com/user-attachments/assets/413cd6db-f65d-4cc9-afd7-7c7a7ecb8d3c)

**Comment by alsino** [comment]
@vogelino 

One more issue I noticed is that the legends on all different layers always have a range from 21 to 40.
Is that a coincidence or is there maybe a mistake. Seems strange that the ranges should be the same across the different units?

**1. UTCI**
![Image](https://github.com/user-attachments/assets/7cf3029f-384c-414e-ba28-d2d4a5adb594)

**2. Relative humidity**
![Image](https://github.com/user-attachments/assets/08301582-6100-4b58-a1f1-555c2fcef0db)

**3. Air temperature**
![Image](https://github.com/user-attachments/assets/0343bb74-f659-4045-8b78-da1c43d42446)

**Comment by vogelino** [comment]
@alsino 

> It seems that the radio button in the left sidebar now does not show the selected layer on startup (see below):

This is now fixed!

> the legends on all different layers always have a range from 21 to 40

This is also fixed!

**Comment by alsino** [comment]
> This is also fixed!

@vogelino Great, but I think the values in the air temperature legend are still not correct.

<img width="309" alt="Image" src="https://github.com/user-attachments/assets/14e9b225-5891-496e-96a0-03638d85bdda" />

**Comment by alsino** [comment]
@vogelino 

Another little detail: When switching from the UTCI layer "By temperature in Celsius" to a different category (e.g. air temperature) and then back to UTCI, the state is not retained and UTCI layer defaults to "By heat stress category").

**Comment by vogelino** [comment]
@alsino @jkittner I also noticed that. But this is coming from the API as is

**Comment by alsino** [comment]
> But this is coming from the API as is

Mhh, is this not a frontend thing?

**Comment by vogelino** [comment]
@alsino The Frontend queries the API to get the scale's min and max values. Those are arriving like this

**Comment by jkittner** [comment]
This is in Kelvin. We will convert it to celsius eventually. Likely in the backend, maybe in the front end.
It is fine as is for now I would say.

The underlying algorithm to generate this is still under development. But that has no effect on the front end.

**Comment by vogelino** [comment]
@jkittner Thx for clarifying! I think it would make sense to unify it so that when using the regular API calls like `snapshot` and when using terracotta, the same unit comes out. I would also favour a conversion of the API side, but if a conversion or different labelling on the frontend is required let me know!

**Comment by alsino** [comment]
> Another little detail: When switching from the UTCI layer "By temperature in Celsius" to a different category (e.g. air temperature) and then back to UTCI, the state is not retained and UTCI layer defaults to "By heat stress category").

@vogelino: I think that was a misunderstanding. I was referring to this above being a frontend matter, not the values in the legend ;)

**Comment by alsino** [comment]
> This is in Kelvin.

Kelvin? Ok, strange. But I agree, this should come from the backend in Celsius units. @jkittner Are you suggesting that we leave this the way it is for now?
